export interface MeridianInfo {
    id: string;
    name: string;
    fullName: string;
    organ: string;
    element: string;
    nature: 'yin' | 'yang';
    location: 'hand' | 'foot';
    points: number;
    pathway: string;
    mainFunctions: string[];
    commonPoints: { name: string; location: string; function: string }[];
}

export interface ExtraordinaryVessel {
    name: string;
    description: string;
    pathway: string;
    functions: string[];
}

// 十二正经完整数据
export const meridians: MeridianInfo[] = [
    {
        id: 'lung',
        name: '肺经',
        fullName: '手太阴肺经',
        organ: '肺',
        element: '金',
        nature: 'yin',
        location: 'hand',
        points: 11,
        pathway: '起于中焦，下络大肠，还循胃口，上膈属肺，从肺系横出腋下，下循臑内，行少阴、心主之前，下肘中，循臂内上骨下廉，入寸口，上鱼，循鱼际，出大指之端。',
        mainFunctions: ['主气司呼吸', '通调水道', '朝百脉'],
        commonPoints: [
            { name: '中府', location: '胸外侧部，云门下1寸', function: '宣肺理气，止咳平喘' },
            { name: '云门', location: '胸外侧部，锁骨下窝', function: '宣肺理气，化痰止咳' },
            { name: '天府', location: '臂内侧，腋前纹头下3寸', function: '理气止咳，清肺热' },
            { name: '侠白', location: '臂内侧，天府下1寸', function: '宽胸理气，止咳平喘' },
            { name: '尺泽', location: '肘横纹中，肱二头肌腱桡侧缘', function: '清肺降逆，化痰止咳' },
            { name: '孔最', location: '前臂掌侧，尺泽与太渊连线上', function: '清热止血，润肺止咳' },
            { name: '列缺', location: '桡骨茎突上方，腕横纹上1.5寸', function: '宣肺解表，通调水道' },
            { name: '经渠', location: '桡骨茎突与桡动脉之间', function: '宣肺理气，止咳平喘' },
            { name: '太渊', location: '腕横纹桡侧，桡动脉搏动处', function: '补肺益气，止咳定喘' },
            { name: '鱼际', location: '第1掌骨中点桡侧缘', function: '清肺热，利咽喉' },
            { name: '少商', location: '拇指桡侧指甲角旁0.1寸', function: '清肺热，利咽喉，开窍醒神' }
        ]
    },
    {
        id: 'large-intestine',
        name: '大肠经',
        fullName: '手阳明大肠经',
        organ: '大肠',
        element: '金',
        nature: 'yang',
        location: 'hand',
        points: 20,
        pathway: '起于大指次指之端，循指上廉，出合谷两骨之间，上入两筋之中，循臂上廉，入肘外廉，上臑外前廉，上 shoulder，出髃骨之前廉，上出于柱骨之会上，下入缺盆，络肺，下膈，属大肠。',
        mainFunctions: ['传化糟粕', '主津液', '主皮毛'],
        commonPoints: [
            { name: '商阳', location: '食指桡侧指甲角旁0.1寸', function: '清热解表，苏厥开窍' },
            { name: '二间', location: '食指桡侧，第2掌指关节前', function: '清热解表，利咽喉' },
            { name: '三间', location: '食指桡侧，第2掌指关节后', function: '清热解表，利咽喉' },
            { name: '合谷', location: '手背第1、2掌骨间，第2掌骨桡侧中点', function: '镇痛解表，通经活络' },
            { name: '阳溪', location: '腕背横纹桡侧，拇短伸肌腱与拇长伸肌腱之间', function: '清热解表，通经活络' },
            { name: '偏历', location: '前臂背面桡侧，阳溪与曲池连线上', function: '宣肺利水，通经活络' },
            { name: '温溜', location: '前臂背面桡侧，阳溪上5寸', function: '清热解表，通经活络' },
            { name: '下廉', location: '前臂背面桡侧，曲池下4寸', function: '调理肠胃，通经活络' },
            { name: '上廉', location: '前臂背面桡侧，曲池下3寸', function: '调理肠胃，通经活络' },
            { name: '手三里', location: '前臂背面桡侧，曲池下2寸', function: '调理肠胃，通经活络' },
            { name: '曲池', location: '肘横纹外侧端，屈肘时肘横纹外侧端', function: '清热解毒，调理肠胃' },
            { name: '肘髎', location: '肘外侧，肱骨外上髁上缘', function: '通经活络，利关节' },
            { name: '手五里', location: '臂外侧，曲池上3寸', function: '通经活络，调理气血' },
            { name: '臂臑', location: '臂外侧，三角肌止点处', function: '通经活络，利关节' },
            { name: '肩髃', location: '肩部，三角肌上，臂外展时肩峰前下方凹陷中', function: '通经活络，利关节' },
            { name: '巨骨', location: '肩胛部，锁骨肩峰端与肩胛冈之间', function: '通经活络，利关节' },
            { name: '天鼎', location: '颈外侧，胸锁乳突肌后缘', function: '利咽喉，化痰散结' },
            { name: '扶突', location: '颈外侧，胸锁乳突肌前后缘之间', function: '利咽喉，化痰散结' },
            { name: '口禾髎', location: '上唇外侧，鼻孔外缘直下', function: '通鼻窍，利咽喉' },
            { name: '迎香', location: '鼻翼外缘中点旁0.5寸', function: '通鼻窍，祛风邪' }
        ]
    },
    {
        id: 'stomach',
        name: '胃经',
        fullName: '足阳明胃经',
        organ: '胃',
        element: '土',
        nature: 'yang',
        location: 'foot',
        points: 45,
        pathway: '起于鼻之交頞中，旁纳太阳之脉，下循鼻外，入上齿中，还出挟口，环唇，下交承浆，却循颐后下廉，出大迎，循颊车，上耳前，过客主人，循发际，至额颅。',
        mainFunctions: ['受纳腐熟水谷', '主降', '生化气血'],
        commonPoints: [
            { name: '承泣', location: '目正视瞳孔直下，眼球与眶下缘之间', function: '明目，止泪' },
            { name: '四白', location: '目正视瞳孔直下，眶下孔处', function: '明目，止痛' },
            { name: '巨髎', location: '瞳孔直下，鼻孔外缘直下', function: '祛风，明目' },
            { name: '地仓', location: '口角外侧0.4寸', function: '祛风，通络' },
            { name: '大迎', location: '下颌角前方，咬肌前缘', function: '祛风，通络' },
            { name: '颊车', location: '下颌角前上方，咬肌隆起处', function: '祛风，利关节' },
            { name: '下关', location: '颧弓与下颌切迹之间', function: '祛风，利关节' },
            { name: '头维', location: '额角发际内0.5寸', function: '祛风，止痛' },
            { name: '人迎', location: '颈部，胸锁乳突肌前缘', function: '调气血，利咽喉' },
            { name: '水突', location: '颈部，胸锁乳突肌前缘', function: '利咽喉，化痰' },
            { name: '气舍', location: '颈部，胸锁乳突肌与锁骨之间', function: '利咽喉，理气' },
            { name: '缺盆', location: '锁骨上窝中央', function: '宽胸，利咽' },
            { name: '气户', location: '锁骨下缘，第1肋间隙', function: '宽胸，理气' },
            { name: '库房', location: '第1肋间隙，乳中线上', function: '宽胸，理气' },
            { name: '屋翳', location: '第2肋间隙，乳中线上', function: '宽胸，理气' },
            { name: '膺窗', location: '第3肋间隙，乳中线上', function: '宽胸，理气' },
            { name: '乳中', location: '乳头中央', function: '通乳' },
            { name: '乳根', location: '乳头直下，第5肋间隙', function: '通乳，宽胸' },
            { name: '不容', location: '上腹部，脐上6寸，前正中线旁2寸', function: '和胃，降逆' },
            { name: '承满', location: '上腹部，脐上5寸，前正中线旁2寸', function: '和胃，降逆' },
            { name: '梁门', location: '上腹部，脐上4寸，前正中线旁2寸', function: '和胃，理气' },
            { name: '关门', location: '上腹部，脐上3寸，前正中线旁2寸', function: '和胃，理气' },
            { name: '太乙', location: '上腹部，脐上2寸，前正中线旁2寸', function: '和胃，理气' },
            { name: '滑肉门', location: '上腹部，脐上1寸，前正中线旁2寸', function: '和胃，理气' },
            { name: '天枢', location: '脐中旁2寸', function: '调理肠胃，止泻' },
            { name: '外陵', location: '下腹部，脐下1寸，前正中线旁2寸', function: '调理肠胃' },
            { name: '大巨', location: '下腹部，脐下2寸，前正中线旁2寸', function: '调理肠胃' },
            { name: '水道', location: '下腹部，脐下3寸，前正中线旁2寸', function: '利水，调经' },
            { name: '归来', location: '下腹部，脐下4寸，前正中线旁2寸', function: '调经，利水' },
            { name: '气冲', location: '腹股沟稍上方，前正中线旁2寸', function: '调经，理气' },
            { name: '髀关', location: '大腿前面，髂前上棘与髌骨外缘连线上', function: '通经活络' },
            { name: '伏兔', location: '大腿前面，髌骨外上缘上6寸', function: '通经活络' },
            { name: '阴市', location: '小腿前外侧，犊鼻下3寸', function: '通经活络' },
            { name: '梁丘', location: '小腿前外侧，犊鼻下3寸', function: '和胃，止痛' },
            { name: '犊鼻', location: '髌骨下缘，髌韧带外侧凹陷中', function: '通经活络，利关节' },
            { name: '足三里', location: '小腿前外侧，犊鼻下3寸', function: '健脾和胃，补中益气' },
            { name: '上巨虚', location: '小腿前外侧，犊鼻下6寸', function: '调理肠胃' },
            { name: '条口', location: '小腿前外侧，犊鼻下8寸', function: '通经活络' },
            { name: '下巨虚', location: '小腿前外侧，犊鼻下9寸', function: '调理肠胃' },
            { name: '丰隆', location: '小腿前外侧，外踝尖上8寸', function: '化痰降逆，和胃' },
            { name: '解溪', location: '足背，踝关节前面中央', function: '清热，安神' },
            { name: '冲阳', location: '足背，第2、3跖骨结合部前方', function: '和胃，安神' },
            { name: '陷谷', location: '足背，第2、3跖骨结合部后方', function: '和胃，清热' },
            { name: '内庭', location: '足背，第2、3趾间缝纹端', function: '清胃热，止痛' },
            { name: '厉兑', location: '足第2趾外侧指甲角旁0.1寸', function: '清胃热，苏厥开窍' }
        ]
    },
    {
        id: 'spleen',
        name: '脾经',
        fullName: '足太阴脾经',
        organ: '脾',
        element: '土',
        nature: 'yin',
        location: 'foot',
        points: 21,
        pathway: '起于大指之端，循指内侧白肉际，过核骨后，上内踝前廉，上踹内，循胫骨后，交出厥阴之前，上膝股内前廉，入腹，属脾，络胃，上膈，挟咽，连舌本，散舌下。',
        mainFunctions: ['运化水谷', '统血', '主升', '主肌肉四肢'],
        commonPoints: [
            { name: '隐白', location: '足大趾内侧指甲角旁0.1寸', function: '健脾统血，调经止血' },
            { name: '大都', location: '足大趾内侧，第1跖趾关节前下方', function: '健脾和胃' },
            { name: '太白', location: '足内侧缘，第1跖骨小头后下方', function: '健脾和胃，化湿' },
            { name: '公孙', location: '足内侧缘，第1跖骨基底前下方', function: '健脾和胃，调冲脉' },
            { name: '商丘', location: '足内踝前下方，舟骨结节与内踝尖连线中点', function: '健脾化湿，通经活络' },
            { name: '三阴交', location: '小腿内侧，内踝尖上3寸，胫骨内侧缘后方', function: '健脾益肾，调肝' },
            { name: '漏谷', location: '小腿内侧，内踝尖上6寸，胫骨内侧缘后方', function: '健脾利湿，通经活络' },
            { name: '地机', location: '小腿内侧，内踝尖上5寸，胫骨内侧缘后方', function: '健脾利湿，调经' },
            { name: '阴陵泉', location: '小腿内侧，胫骨内侧髁后下方凹陷中', function: '健脾利湿，通经活络' },
            { name: '血海', location: '大腿内侧，髌骨内上缘上2寸', function: '调血活血，健脾' },
            { name: '箕门', location: '大腿内侧，血海与冲门连线上', function: '健脾利湿，调经' },
            { name: '冲门', location: '腹股沟外侧，髂前上棘下方', function: '健脾理气，调经' },
            { name: '府舍', location: '下腹部，脐下4.3寸，前正中线旁4寸', function: '健脾理气' },
            { name: '腹结', location: '下腹部，脐下1.3寸，前正中线旁4寸', function: '健脾理气，调经' },
            { name: '大横', location: '腹部，脐中旁4寸', function: '健脾理气，调肠胃' },
            { name: '腹哀', location: '上腹部，脐上3寸，前正中线旁4寸', function: '健脾和胃，理气' },
            { name: '食窦', location: '胸外侧部，第5肋间隙，腋中线上', function: '宽胸理气，和胃' },
            { name: '天溪', location: '胸外侧部，第4肋间隙，腋中线上', function: '宽胸理气，通乳' },
            { name: '胸乡', location: '胸外侧部，第3肋间隙，腋中线上', function: '宽胸理气' },
            { name: '周荣', location: '胸外侧部，第2肋间隙，腋中线上', function: '宽胸理气，止咳' },
            { name: '大包', location: '胸外侧部，第6肋间隙，腋中线上', function: '宽胸理气，统血' }
        ]
    },
    {
        id: 'heart',
        name: '心经',
        fullName: '手少阴心经',
        organ: '心',
        element: '火',
        nature: 'yin',
        location: 'hand',
        points: 9,
        pathway: '起于心中，出属心系，下膈，历络三焦；其支者，循胸出胁，下腋三寸，上抵腋下，循臑内，行太阴、少阴之间，入肘中，下臂行两筋之间，入掌中，循中指，出其端。',
        mainFunctions: ['主血脉', '主神明', '主汗液'],
        commonPoints: [
            { name: '极泉', location: '腋窝顶点，腋动脉搏动处', function: '宽胸理气，调心律' },
            { name: '青灵', location: '臂内侧，极泉下3寸', function: '宽胸理气，安神' },
            { name: '少海', location: '肘内侧，肘横纹内侧端', function: '清心安神，通经活络' },
            { name: '灵道', location: '前臂内侧，神门上1.5寸', function: '清心安神，通经活络' },
            { name: '通里', location: '前臂内侧，神门上1寸', function: '清心安神，通经活络' },
            { name: '阴郄', location: '前臂内侧，神门上0.5寸', function: '清心安神，止汗' },
            { name: '神门', location: '腕横纹尺侧端，尺侧腕屈肌腱桡侧缘', function: '安神定志，清心火' },
            { name: '少府', location: '手掌，第4、5掌骨之间', function: '清心火，安神' },
            { name: '少冲', location: '小指桡侧指甲角旁0.1寸', function: '清心火，开窍醒神' }
        ]
    },
    {
        id: 'small-intestine',
        name: '小肠经',
        fullName: '手太阳小肠经',
        organ: '小肠',
        element: '火',
        nature: 'yang',
        location: 'hand',
        points: 19,
        pathway: '起于小指之端，循手外侧上腕，出踝中，直上循臂骨下廉，出肘内侧两筋之间，上循臑外后廉，出肩解，绕肩胛，交肩上，入缺盆，络心，循咽下膈，抵胃，属小肠。',
        mainFunctions: ['受盛化物', '泌别清浊', '主液'],
        commonPoints: [
            { name: '少泽', location: '小指尺侧指甲角旁0.1寸', function: '清热解表，通乳' },
            { name: '前谷', location: '小指尺侧，第5掌指关节前', function: '清热解表，通经活络' },
            { name: '后溪', location: '小指尺侧，第5掌指关节后', function: '清热解表，通经活络' },
            { name: '腕骨', location: '手背尺侧，第5掌骨基底与钩骨之间', function: '清热解表，通经活络' },
            { name: '阳谷', location: '腕背横纹尺侧端，尺骨茎突与三角骨之间', function: '清热解表，安神' },
            { name: '养老', location: '前臂背面尺侧，阳谷与小海连线上', function: '清热明目，舒筋活络' },
            { name: '支正', location: '前臂背面尺侧，阳谷上5寸', function: '清心安神，通经活络' },
            { name: '小海', location: '肘内侧，尺骨鹰嘴与肱骨内上髁之间', function: '清热解表，安神' },
            { name: '肩贞', location: '肩胛部，肩关节后下方', function: '通经活络，利关节' },
            { name: '臑俞', location: '肩胛部，肩胛冈下缘', function: '通经活络，利关节' },
            { name: '天宗', location: '肩胛部，肩胛冈下缘中点下1寸', function: '通经活络，宽胸理气' },
            { name: '秉风', location: '肩胛部，肩胛冈上缘中点', function: '通经活络，利关节' },
            { name: '曲垣', location: '肩胛部，肩胛冈内侧端上方', function: '通经活络，利关节' },
            { name: '肩外俞', location: '背部，第1胸椎棘突下，旁开3寸', function: '通经活络，利关节' },
            { name: '肩中俞', location: '背部，第7颈椎棘突下，旁开2寸', function: '通经活络，利关节' },
            { name: '天窗', location: '颈外侧，胸锁乳突肌后缘', function: '利咽喉，聪耳' },
            { name: '天容', location: '颈部，下颌角后方', function: '利咽喉，消肿' },
            { name: '颧髎', location: '面部，颧骨下缘中点', function: '祛风，通络' },
            { name: '听宫', location: '面部，耳屏前，下颌髁状突后方', function: '聪耳，开窍' }
        ]
    },
    {
        id: 'bladder',
        name: '膀胱经',
        fullName: '足太阳膀胱经',
        organ: '膀胱',
        element: '水',
        nature: 'yang',
        location: 'foot',
        points: 67,
        pathway: '起于目内眦，上额，交巅；其支者，从巅至耳上角；其直者，从巅入络脑，还出别下项，循肩膊内，挟脊抵腰中，入循膂，络肾，属膀胱。',
        mainFunctions: ['贮尿排尿', '气化', '主表'],
        commonPoints: [
            { name: '睛明', location: '目内眦角稍上方', function: '明目，止泪' },
            { name: '攒竹', location: '眉头，眉毛内侧端', function: '明目，止痛' },
            { name: '眉冲', location: '眉头上方，神庭旁1.5寸', function: '明目，止痛' },
            { name: '曲差', location: '前发际正中旁1.5寸', function: '明目，止痛' },
            { name: '五处', location: '前发际正中旁1.5寸，曲差后1寸', function: '明目，止痛' },
            { name: '承光', location: '前发际正中旁1.5寸，五处后1寸', function: '明目，止痛' },
            { name: '通天', location: '前发际正中旁1.5寸，承光后1寸', function: '明目，通鼻窍' },
            { name: '络却', location: '前发际正中旁1.5寸，通天后1寸', function: '明目，安神' },
            { name: '玉枕', location: '后发际正中旁1.3寸', function: '明目，安神' },
            { name: '天柱', location: '后发际正中旁1.3寸，斜方肌外缘', function: '祛风，通络' },
            { name: '大杼', location: '背部，第1胸椎棘突下，旁开1.5寸', function: '祛风，通络' },
            { name: '风门', location: '背部，第2胸椎棘突下，旁开1.5寸', function: '祛风解表' },
            { name: '肺俞', location: '背部，第3胸椎棘突下，旁开1.5寸', function: '宣肺理气，止咳平喘' },
            { name: '厥阴俞', location: '背部，第4胸椎棘突下，旁开1.5寸', function: '宽胸理气，安神' },
            { name: '心俞', location: '背部，第5胸椎棘突下，旁开1.5寸', function: '养心安神，宽胸理气' },
            { name: '督俞', location: '背部，第6胸椎棘突下，旁开1.5寸', function: '宽胸理气，强心' },
            { name: '膈俞', location: '背部，第7胸椎棘突下，旁开1.5寸', function: '宽胸理气，活血' },
            { name: '肝俞', location: '背部，第9胸椎棘突下，旁开1.5寸', function: '疏肝理气，明目' },
            { name: '胆俞', location: '背部，第10胸椎棘突下，旁开1.5寸', function: '疏肝利胆，清热' },
            { name: '脾俞', location: '背部，第11胸椎棘突下，旁开1.5寸', function: '健脾和胃，利湿' },
            { name: '胃俞', location: '背部，第12胸椎棘突下，旁开1.5寸', function: '健脾和胃，理气' },
            { name: '三焦俞', location: '背部，第1腰椎棘突下，旁开1.5寸', function: '调理三焦，利水' },
            { name: '肾俞', location: '背部，第2腰椎棘突下，旁开1.5寸', function: '补肾壮阳，利水' },
            { name: '气海俞', location: '背部，第3腰椎棘突下，旁开1.5寸', function: '补肾壮阳，理气' },
            { name: '大肠俞', location: '背部，第4腰椎棘突下，旁开1.5寸', function: '调理肠胃，止泻' },
            { name: '关元俞', location: '背部，第5腰椎棘突下，旁开1.5寸', function: '补肾壮阳，调经' },
            { name: '小肠俞', location: '骶部，第1骶椎棘突下，旁开1.5寸', function: '调理小肠，利水' },
            { name: '膀胱俞', location: '骶部，第2骶椎棘突下，旁开1.5寸', function: '调理膀胱，利水' },
            { name: '中膂俞', location: '骶部，第3骶椎棘突下，旁开1.5寸', function: '调理下焦，利水' },
            { name: '白环俞', location: '骶部，第4骶椎棘突下，旁开1.5寸', function: '调经，利水' },
            { name: '上髎', location: '骶部，第1骶后孔中', function: '调经，利水' },
            { name: '次髎', location: '骶部，第2骶后孔中', function: '调经，利水' },
            { name: '中髎', location: '骶部，第3骶后孔中', function: '调经，利水' },
            { name: '下髎', location: '骶部，第4骶后孔中', function: '调经，利水' },
            { name: '会阳', location: '骶部，尾骨尖旁0.5寸', function: '调经，止泻' },
            { name: '承扶', location: '大腿后面，臀横纹中点', function: '通经活络，强腰' },
            { name: '殷门', location: '大腿后面，承扶与委中连线上', function: '通经活络，强腰' },
            { name: '浮郄', location: '大腿后面，委阳外上方1寸', function: '通经活络，利关节' },
            { name: '委阳', location: '腘横纹外侧端', function: '通经活络，利关节' },
            { name: '委中', location: '腘横纹中点', function: '通经活络，清热' },
            { name: '附分', location: '背部，第2胸椎棘突下，旁开3寸', function: '通经活络，止痛' },
            { name: '魄户', location: '背部，第3胸椎棘突下，旁开3寸', function: '宣肺理气，止咳' },
            { name: '膏肓', location: '背部，第4胸椎棘突下，旁开3寸', function: '补虚，强身' },
            { name: '神堂', location: '背部，第5胸椎棘突下，旁开3寸', function: '宽胸理气，安神' },
            { name: '譩譆', location: '背部，第6胸椎棘突下，旁开3寸', function: '宽胸理气，止咳' },
            { name: '膈关', location: '背部，第7胸椎棘突下，旁开3寸', function: '宽胸理气，和胃' },
            { name: '魂门', location: '背部，第9胸椎棘突下，旁开3寸', function: '疏肝理气，安神' },
            { name: '阳纲', location: '背部，第10胸椎棘突下，旁开3寸', function: '疏肝利胆，和胃' },
            { name: '意舍', location: '背部，第11胸椎棘突下，旁开3寸', function: '健脾和胃，安神' },
            { name: '胃仓', location: '背部，第12胸椎棘突下，旁开3寸', function: '健脾和胃，消食' },
            { name: '肓门', location: '背部，第1腰椎棘突下，旁开3寸', function: '调理三焦，消积' },
            { name: '志室', location: '背部，第2腰椎棘突下，旁开3寸', function: '补肾壮阳，强志' },
            { name: '胞肓', location: '背部，第2骶椎棘突下，旁开3寸', function: '调理下焦，利水' },
            { name: '秩边', location: '臀部，第4骶椎棘突下，旁开3寸', function: '调理下焦，通便' },
            { name: '合阳', location: '小腿后面，委中下2寸', function: '通经活络，调经' },
            { name: '承筋', location: '小腿后面，委中下5寸', function: '通经活络，舒筋' },
            { name: '承山', location: '小腿后面，委中与昆仑连线上', function: '通经活络，舒筋' },
            { name: '飞扬', location: '小腿外侧，昆仑上7寸', function: '通经活络，清头目' },
            { name: '跗阳', location: '小腿外侧，昆仑上3寸', function: '通经活络，利关节' },
            { name: '昆仑', location: '外踝后方，外踝尖与跟腱之间', function: '通经活络，强腰膝' },
            { name: '仆参', location: '足外侧，昆仑下方', function: '通经活络，利关节' },
            { name: '申脉', location: '足外侧，外踝直下方凹陷中', function: '通经活络，安神' },
            { name: '金门', location: '足外侧，第5跖骨基底前方', function: '通经活络，安神' },
            { name: '京骨', location: '足外侧，第5跖骨粗隆下方', function: '通经活络，明目' },
            { name: '束骨', location: '足外侧，第5跖趾关节后方', function: '通经活络，明目' },
            { name: '足通谷', location: '足外侧，第5趾跖趾关节前方', function: '通经活络，清头目' },
            { name: '至阴', location: '足小趾外侧指甲角旁0.1寸', function: '通经活络，矫正胎位' }
        ]
    },
    {
        id: 'kidney',
        name: '肾经',
        fullName: '足少阴肾经',
        organ: '肾',
        element: '水',
        nature: 'yin',
        location: 'foot',
        points: 27,
        pathway: '起于小指之下，邪走足心，出于然谷之下，循内踝之后，别入跟中，以上踹内，出腘内廉，上股内后廉，贯脊属肾，络膀胱。',
        mainFunctions: ['藏精', '主水', '主骨生髓', '开窍于耳'],
        commonPoints: [
            { name: '涌泉', location: '足底，足前部凹陷处', function: '补肾壮阳，清热安神' },
            { name: '然谷', location: '足内侧，舟骨粗隆下方', function: '补肾壮阳，调经' },
            { name: '太溪', location: '足内侧，内踝后方，内踝尖与跟腱之间', function: '补肾壮阳，滋阴' },
            { name: '大钟', location: '足内侧，内踝后下方', function: '补肾壮阳，利水' },
            { name: '水泉', location: '足内侧，太溪下1寸', function: '补肾利水，调经' },
            { name: '照海', location: '足内侧，内踝尖下方凹陷中', function: '补肾滋阴，调经' },
            { name: '复溜', location: '小腿内侧，太溪上2寸', function: '补肾利水，止汗' },
            { name: '交信', location: '小腿内侧，太溪上2寸，胫骨内侧缘', function: '补肾调经，利水' },
            { name: '筑宾', location: '小腿内侧，太溪上5寸', function: '补肾安神，利水' },
            { name: '阴谷', location: '腘内侧，半腱肌肌腱与半膜肌肌腱之间', function: '补肾利水，调经' },
            { name: '横骨', location: '下腹部，脐下5寸，前正中线旁0.5寸', function: '补肾壮阳，利水' },
            { name: '大赫', location: '下腹部，脐下4寸，前正中线旁0.5寸', function: '补肾壮阳，调经' },
            { name: '气穴', location: '下腹部，脐下3寸，前正中线旁0.5寸', function: '补肾理气，调经' },
            { name: '四满', location: '下腹部，脐下2寸，前正中线旁0.5寸', function: '补肾理气，利水' },
            { name: '中注', location: '下腹部，脐下1寸，前正中线旁0.5寸', function: '补肾理气，调经' },
            { name: '肓俞', location: '腹部，脐中旁0.5寸', function: '补肾理气，调肠胃' },
            { name: '商曲', location: '上腹部，脐上2寸，前正中线旁0.5寸', function: '补肾和胃，理气' },
            { name: '石关', location: '上腹部，脐上3寸，前正中线旁0.5寸', function: '补肾和胃，理气' },
            { name: '阴都', location: '上腹部，脐上4寸，前正中线旁0.5寸', function: '补肾和胃，理气' },
            { name: '腹通谷', location: '上腹部，脐上5寸，前正中线旁0.5寸', function: '补肾和胃，理气' },
            { name: '幽门', location: '上腹部，脐上6寸，前正中线旁0.5寸', function: '补肾和胃，降逆' },
            { name: '步廊', location: '胸部，第5肋间隙，前正中线旁2寸', function: '补肾宽胸，理气' },
            { name: '神封', location: '胸部，第4肋间隙，前正中线旁2寸', function: '补肾宽胸，安神' },
            { name: '灵墟', location: '胸部，第3肋间隙，前正中线旁2寸', function: '补肾宽胸，理气' },
            { name: '神藏', location: '胸部，第2肋间隙，前正中线旁2寸', function: '补肾宽胸，安神' },
            { name: '彧中', location: '胸部，第1肋间隙，前正中线旁2寸', function: '补肾宽胸，理气' },
            { name: '俞府', location: '胸部，锁骨下缘，前正中线旁2寸', function: '补肾宽胸，止咳' }
        ]
    },
    {
        id: 'pericardium',
        name: '心包经',
        fullName: '手厥阴心包经',
        organ: '心包',
        element: '火',
        nature: 'yin',
        location: 'hand',
        points: 9,
        pathway: '起于胸中，出属心包络，下膈，历络三焦；其支者，循胸出胁，下腋三寸，上抵腋下，循臑内，行太阴、少阴之间，入肘中，下臂行两筋之间，入掌中，循中指，出其端。',
        mainFunctions: ['代心受邪', '主血脉', '主神明'],
        commonPoints: [
            { name: '天池', location: '胸部，第4肋间隙，乳头外1寸', function: '宽胸理气，通乳' },
            { name: '天泉', location: '臂内侧，腋前纹头下2寸', function: '宽胸理气，安神' },
            { name: '曲泽', location: '肘横纹中，肱二头肌腱尺侧缘', function: '清心火，和胃' },
            { name: '郄门', location: '前臂内侧，曲泽与大陵连线上', function: '清心火，安神' },
            { name: '间使', location: '前臂内侧，大陵上3寸', function: '清心火，安神' },
            { name: '内关', location: '前臂内侧，大陵上2寸', function: '安神定志，和胃' },
            { name: '大陵', location: '腕横纹中点，掌长肌腱与桡侧腕屈肌腱之间', function: '清心火，安神' },
            { name: '劳宫', location: '手掌心，第2、3掌骨之间', function: '清心火，安神' },
            { name: '中冲', location: '中指尖端中央', function: '清心火，开窍醒神' }
        ]
    },
    {
        id: 'triple-heater',
        name: '三焦经',
        fullName: '手少阳三焦经',
        organ: '三焦',
        element: '火',
        nature: 'yang',
        location: 'hand',
        points: 23,
        pathway: '起于小指次指之端，上出两指之间，循手表腕，出臂外两骨之间，上贯肘，循臑外上肩，而交出足少阳之后，入缺盆，布膻中，散络心包，下膈，循属三焦。',
        mainFunctions: ['通调水道', '运化水谷', '主气'],
        commonPoints: [
            { name: '关冲', location: '无名指尺侧指甲角旁0.1寸', function: '清热开窍，通经活络' },
            { name: '液门', location: '手背，第4、5指间缝纹端', function: '清热利咽，通经活络' },
            { name: '中渚', location: '手背，第4、5掌骨间凹陷中', function: '清热利咽，通经活络' },
            { name: '阳池', location: '腕背横纹中，指总伸肌腱尺侧缘', function: '通调三焦，利关节' },
            { name: '外关', location: '前臂背侧，阳池上2寸', function: '解表清热，通经活络' },
            { name: '支沟', location: '前臂背侧，阳池上3寸', function: '通调三焦，理气' },
            { name: '会宗', location: '前臂背侧，支沟桡侧1寸', function: '清热安神，通经活络' },
            { name: '三阳络', location: '前臂背侧，阳池上4寸', function: '通调三焦，聪耳' },
            { name: '四渎', location: '前臂背侧，阳池上5寸', function: '清热利咽，聪耳' },
            { name: '天井', location: '肘后，尺骨鹰嘴上1寸凹陷中', function: '清热散结，通经活络' },
            { name: '清冷渊', location: '臂外侧，天井上1寸', function: '清热散结，通经活络' },
            { name: '消泺', location: '臂外侧，天井上2寸', function: '清热散结，通经活络' },
            { name: '臑会', location: '臂外侧，肩髎下3寸', function: '通经活络，利关节' },
            { name: '肩髎', location: '肩部，肩峰后下方凹陷中', function: '通经活络，利关节' },
            { name: '天髎', location: '肩胛部，肩井与曲垣连线中点', function: '通经活络，利关节' },
            { name: '天牖', location: '颈外侧，胸锁乳突肌后缘', function: '聪耳明目，利咽喉' },
            { name: '翳风', location: '耳后，乳突与下颌角之间', function: '聪耳，祛风' },
            { name: '瘈脉', location: '耳后，乳突后上方', function: '聪耳，安神' },
            { name: '颅息', location: '耳后，瘈脉与角孙连线中点', function: '聪耳，安神' },
            { name: '角孙', location: '耳尖直上，发际内', function: '聪耳，明目' },
            { name: '耳门', location: '耳前，耳屏上切迹前', function: '聪耳，利关节' },
            { name: '和髎', location: '耳前，耳屏前上方', function: '聪耳，利关节' },
            { name: '丝竹空', location: '眉梢凹陷中', function: '明目，止痛' }
        ]
    },
    {
        id: 'gallbladder',
        name: '胆经',
        fullName: '足少阳胆经',
        organ: '胆',
        element: '木',
        nature: 'yang',
        location: 'foot',
        points: 44,
        pathway: '起于目锐眦，上抵头角，下耳后，循颈行手少阳之前，至肩上，却交出手少阳之后，入缺盆；其支者，从耳后入耳中，出走耳前，至目锐眦后。',
        mainFunctions: ['贮藏排泄胆汁', '主决断', '主筋'],
        commonPoints: [
            { name: '瞳子髎', location: '目外眦旁0.5寸', function: '明目，止痛' },
            { name: '听会', location: '耳前，耳屏间切迹前方', function: '聪耳，利关节' },
            { name: '上关', location: '耳前，颧弓上缘凹陷中', function: '聪耳，利关节' },
            { name: '颔厌', location: '头侧，发际内，额角上方', function: '明目，止痛' },
            { name: '悬颅', location: '头侧，发际内，颔厌后1寸', function: '明目，止痛' },
            { name: '悬厘', location: '头侧，发际内，悬颅后1寸', function: '明目，止痛' },
            { name: '曲鬓', location: '耳前上方，发际内', function: '明目，利关节' },
            { name: '率谷', location: '耳尖直上，发际上1.5寸', function: '明目，止痛' },
            { name: '天冲', location: '耳后上方，率谷后0.5寸', function: '明目，安神' },
            { name: '浮白', location: '耳后上方，天冲后1寸', function: '聪耳，安神' },
            { name: '头窍阴', location: '耳后上方，浮白后1寸', function: '聪耳，安神' },
            { name: '完骨', location: '耳后，乳突后下方凹陷中', function: '聪耳，安神' },
            { name: '本神', location: '头侧，前发际上0.5寸，神庭旁3寸', function: '安神，止痛' },
            { name: '阳白', location: '额部，瞳孔直上，眉上1寸', function: '明目，止痛' },
            { name: '头临泣', location: '头部，瞳孔直上，前发际上0.5寸', function: '明目，止痛' },
            { name: '目窗', location: '头部，瞳孔直上，前发际上1.5寸', function: '明目，止痛' },
            { name: '正营', location: '头部，瞳孔直上，前发际上2.5寸', function: '明目，止痛' },
            { name: '承灵', location: '头部，瞳孔直上，前发际上4寸', function: '明目，止痛' },
            { name: '脑空', location: '头后部，枕外隆凸上方', function: '明目，安神' },
            { name: '风池', location: '项部，枕骨下，胸锁乳突肌与斜方肌之间', function: '祛风解表，明目' },
            { name: '肩井', location: '肩上，大椎与肩峰连线中点', function: '通经活络，利关节' },
            { name: '渊腋', location: '胸外侧，腋中线，第4肋间隙', function: '宽胸理气' },
            { name: '辄筋', location: '胸外侧，腋中线，第4肋间隙', function: '宽胸理气' },
            { name: '日月', location: '胸外侧，第7肋间隙，乳头直下', function: '疏肝利胆，和胃' },
            { name: '京门', location: '侧腰部，第12肋骨游离端下方', function: '疏肝利胆，利水' },
            { name: '带脉', location: '侧腰部，第11肋骨游离端下方', function: '疏肝理气，调经' },
            { name: '五枢', location: '侧腹部，髂前上棘前下方', function: '疏肝理气，调经' },
            { name: '维道', location: '侧腹部，髂前上棘前下方', function: '疏肝理气，调经' },
            { name: '居髎', location: '臀部，髂前上棘与股骨大转子连线中点', function: '疏肝理气，强腰' },
            { name: '环跳', location: '臀部，股骨大转子与骶管裂孔连线中点', function: '疏肝理气，强腰' },
            { name: '风市', location: '大腿外侧，膝上7寸', function: '祛风湿，通经活络' },
            { name: '中渎', location: '大腿外侧，膝上5寸', function: '疏肝理气，通经活络' },
            { name: '膝阳关', location: '膝外侧，股骨外上髁上方', function: '疏肝理气，利关节' },
            { name: '阳陵泉', location: '小腿外侧，腓骨小头前下方凹陷中', function: '疏肝利胆，舒筋' },
            { name: '阳交', location: '小腿外侧，外踝上7寸', function: '疏肝理气，通经活络' },
            { name: '外丘', location: '小腿外侧，外踝上7寸', function: '疏肝明目，通经活络' },
            { name: '光明', location: '小腿外侧，外踝上5寸', function: '疏肝明目，通经活络' },
            { name: '阳辅', location: '小腿外侧，外踝上4寸', function: '疏肝理气，通经活络' },
            { name: '悬钟', location: '小腿外侧，外踝上3寸', function: '疏肝理气，强筋骨' },
            { name: '丘墟', location: '足外踝前下方，距骨前方凹陷中', function: '疏肝理气，利关节' },
            { name: '足临泣', location: '足背，第4、5跖骨结合部前方', function: '疏肝理气，明目' },
            { name: '地五会', location: '足背，第4、5跖骨间', function: '疏肝理气，通经活络' },
            { name: '侠溪', location: '足背，第4、5趾间', function: '疏肝理气，清热' },
            { name: '足窍阴', location: '足第4趾外侧指甲角旁0.1寸', function: '疏肝理气，开窍醒神' }
        ]
    },
    {
        id: 'liver',
        name: '肝经',
        fullName: '足厥阴肝经',
        organ: '肝',
        element: '木',
        nature: 'yin',
        location: 'foot',
        points: 14,
        pathway: '起于大指丛毛之际，上循足跗上廉，去内踝一寸，上踝八寸，交出太阴之后，上腘内廉，循股阴，入毛中，过阴器，抵小腹，挟胃，属肝，络胆，上贯膈，布胁肋，循喉咙之后，上入颃颡，连目系，上出额，与督脉会于巅。',
        mainFunctions: ['疏泄', '藏血', '主筋'],
        commonPoints: [
            { name: '大敦', location: '足大趾外侧指甲角旁0.1寸', function: '疏肝理气，调经止血' },
            { name: '行间', location: '足背，第1、2趾间', function: '疏肝泻火，调经' },
            { name: '太冲', location: '足背，第1、2跖骨结合部前方凹陷中', function: '疏肝理气，调经止痛' },
            { name: '中封', location: '足内踝前，胫骨前肌腱内侧凹陷中', function: '疏肝理气，利水' },
            { name: '蠡沟', location: '小腿内侧，内踝上5寸', function: '疏肝理气，调经' },
            { name: '中都', location: '小腿内侧，内踝上7寸', function: '疏肝理气，调经' },
            { name: '膝关', location: '膝内侧，胫骨内侧髁下方', function: '疏肝理气，利关节' },
            { name: '曲泉', location: '膝内侧，半腱肌、半膜肌止点前缘', function: '疏肝理气，利水' },
            { name: '阴包', location: '大腿内侧，膝上4寸', function: '疏肝理气，调经' },
            { name: '足五里', location: '大腿内侧，气冲下3寸', function: '疏肝理气，调经' },
            { name: '阴廉', location: '大腿内侧，气冲下2寸', function: '疏肝理气，调经' },
            { name: '急脉', location: '耻骨结节外侧，气冲外下方', function: '疏肝理气，调经' },
            { name: '章门', location: '侧腹部，第11肋骨游离端下方', function: '疏肝健脾，理气' },
            { name: '期门', location: '胸部，第6肋间隙', function: '疏肝理气，和胃' }
        ]
    }
];

// 奇经八脉数据
export const extraordinaryVessels: ExtraordinaryVessel[] = [
    {
        name: '督脉',
        description: '阳脉之海，总督一身之阳经',
        pathway: '起于小腹内，下出会阴，后行于脊柱内，上至风府，入脑，上巅，循额，至鼻柱',
        functions: ['调节阳经气血', '主生殖机能', '主神志']
    },
    {
        name: '任脉',
        description: '阴脉之海，总任一身之阴经',
        pathway: '起于小腹内，下出会阴，前行于腹面正中线，上至咽喉，环绕口唇',
        functions: ['调节阴经气血', '主妊养胞胎', '主生殖']
    },
    {
        name: '冲脉',
        description: '十二经脉之海，能调节十二经气血',
        pathway: '起于小腹内，挟脐上行，至胸中而散',
        functions: ['调节十二经气血', '主血海', '调节月经']
    },
    {
        name: '带脉',
        description: '约束诸经，如带束身',
        pathway: '起于季胁，斜向下行，环腰一周',
        functions: ['约束纵行诸经', '固摄下焦', '调节带下']
    },
    {
        name: '阴跷脉',
        description: '主一身左右之阴',
        pathway: '起于然谷，循内踝上行，至咽喉，交贯冲脉',
        functions: ['调节下肢运动', '主睡眠', '调节阴阳']
    },
    {
        name: '阳跷脉',
        description: '主一身左右之阳',
        pathway: '起于申脉，循外踝上行，至目内眦，上额与足太阳经合',
        functions: ['调节下肢运动', '主觉醒', '调节阴阳']
    },
    {
        name: '阴维脉',
        description: '维系诸阴经',
        pathway: '起于小腿内侧，上行至腹，胸，咽喉',
        functions: ['联络阴经', '调节情志', '主内守']
    },
    {
        name: '阳维脉',
        description: '维系诸阳经',
        pathway: '起于足跗外侧，上行至项后，额，耳后',
        functions: ['联络阳经', '调节情志', '主外卫']
    }
];